use veritabani
go
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Filiz','Öngüt',1080)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Fuat','Aslým',1081)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Sevil','Yüksel',1082)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Ýsmail','Gül',1083)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Emine','Tiryaki',1084)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Ali','Aydýn',1085)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Murat','Demirel',1086)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Gazi','Erman',1087)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Simay','Özmen',1088)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Selda','Yýlmaz',1089)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Havin','Parin',1090)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Mehmet','Taþkýn',1091)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Gökay','Erder',1092)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Özlem','Gündoðdu',1093)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Emine','Çelenk',1094)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Burak','Çiftçi',1095)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Süha','Tozkan',1096)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Onur','Þeker',1097)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Sema','Kadayýfçý',1098)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Derin','Dal',1099)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Esen','Erdoðanlý',1100)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Mine','Çelik',1101)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Gökhan','Atlý',1102)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Yücel','Çetin',1103)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Zeynep','Yýldýz',1104)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Ýsa','Kuzu',1105)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Taner','Ayar',1106)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Simge','Ümitdar',1107)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Natalya','Gökçe',1108)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Recep','Göktürk',1109)
INSERT tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id) VALUES ('Onur','Kuzik',1110)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Erdoðan','Gök',1050)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Emre','Yurtseven',1051)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Berkay','Ayyýldýz',1052)

insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Özcan','Çiftçi',1053)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Betül','Öz',1054)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Kübra','Kurt',1055)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Ýpek','Çift',1057)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Ýrem','Kan',1056)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Derya','Gezer',1058)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Gökçe','Gün',1059)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Berke','Öz',1060)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Pýnar','Yiðit',1061)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Beyza','Pazar',1062)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Gözde','Kaya',1063)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Pýnar','Yiðit',1064)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Þenol','Er',1065)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Avni','Çay',1066)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Gökçin','Bozan',1067)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Tuðçe','Gümüþ',1068)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Ýleyda','Elma',1069)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Ali','Kan',1070)

insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Kader','Yeþil',1071)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Seda','Baltalý',1072)

insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Seda','Avcý',1073)

insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Tolga','Soyal',1074)

insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Melis','Yýlmaz',1075)

insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Ali','Sarý',1076)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Cem','Kirmit',1077)
insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Yunus','Çiðdem',1078)

insert into tbl_musteriler(musteri_adi,musteri_soyadi,musteri_iletisim_id)
values('Aykut','Elmas',1079)